export const Action_List_Github_Repository = 'Action_Github_Repository'
export const Action_List_Github_Author = 'Action_Github_Author'
export const Action_List_Article_Detail = 'Action_List_Article_Detail'
export const Action_List_Article_Author = 'Action_List_Article_Author'
export const Action_List_Article_Tag = 'Action_List_Article_Tag'
export const Action_List_Article_Range = 'Action_List_Article_Range'

export const Action_Header_Right_Auth = 'Action_Header_Right_Auth'

export const Action_Channel_Type_Article = 'Action_Channel_Type_Article'
export const Action_Channel_Type_Github = 'Action_Channel_Type_Github'
export const Action_Channel_Type_Grammar = 'Action_Channel_Type_Grammar'
export const Action_Channel_Type_Word = 'Action_Channel_Type_Word'

export const Action_Admin_Channel_Type_User = 'Action_Admin_Channel_Type_User'
export const Action_Admin_Channel_Type_Channel = 'Action_Admin_Channel_Type_Channel'
export const Action_Admin_Channel_Type_Article = 'Action_Admin_Channel_Type_Article'
export const Action_Admin_Channel_Type_Word = 'Action_Admin_Channel_Type_Word'
export const Action_Admin_Channel_Type_Setting = 'Action_Admin_Channel_Type_Setting'
export const Action_Admin_Channel_Type_Crawler = 'Action_Admin_Channel_Type_Crawler'
export const Action_Admin_Channel_Type_Logout = 'Action_Admin_Channel_Type_Logout'

export const Action_Display_List_Article = 'Action_Display_List_Article'
export const Action_Display_List_Github = 'Action_Display_List_Github'
export const Action_Display_List_Deutsch = 'Action_Display_List_Deutsch'

export const Action_List_Filter_Confirm = 'Action_List_Filter_Confirm'
export const Action_Filter_List_Article_Confirm = 'Action_Filter_List_Article_Confirm'
export const Action_Filter_List_Github_Confirm = 'Action_Filter_List_Github_Confirm'
export const Action_Admin_Article_List_Filter_Confirm = 'Action_Admin_Article_List_Filter_Confirm'

export const Action_Admin_Word_List_Sort = 'Action_Admin_Word_List_Sort'
export const Action_Admin_Word_List_Page = 'Action_Admin_Word_List_Page'
export const Action_Admin_Word_List_Filter_Confirm = 'Action_Admin_Word_List_Filter_Confirm'
export const Action_Admin_Word_List_Item_Unregel = 'Action_Admin_Word_List_Item_Unregel'
export const Action_Admin_Word_List_Item_Recommend = 'Action_Admin_Word_List_Item_Recommend'
export const Action_Admin_Word_List_Item_Approval = 'Action_Admin_Word_List_Item_Approval'
export const Action_Admin_Word_List_Item_Modify = 'Action_Admin_Word_List_Item_Modify'

export const Action_Admin_New_Article_Confirm = 'Action_Admin_New_Article_Confirm'
export const Action_Admin_New_Word_Confirm = 'Action_Admin_New_Word_Confirm'